<main id="terms" class="inner-bottom-md">
	<div class="container">
		<section class="section section-page-title">
			<div class="page-header">
				<h2 class="page-title">Quy định và điều khoản</h2>
				<p class="page-subtitle">Được xác nhận lần cuối vào ngày 30-5-2020</p>
			</div>
		</section><!-- /.section-page-title -->
		<section class="section intellectual-property inner-bottom-xs">
			<h2>Quyền sỡ hữu trí tuệ</h2>
			<ol>
				<li>Quyền sở hữu trí tuệ là một nội dung luật học có phạm vi điều chỉnh các quyền sở hữu công nghệ, tác quyền và những quyền liên quan. Quyền sở hữu trí tuệ bao gồm quyền được luật pháp bảo hộ chống lại mọi hình thức xâm phạm tài sản sở hữu trí tuệ. Lúc đầu, mỗi quốc gia có một quy định riêng nhưng kể từ ngày Công ước Berne ra đời và nhất là sau khi thành lập Tổ chức Sở hữu trí tuệ thế giới (WIPO) năm 1967, các quy định này dần trở nên thống nhất do các nước cùng công nhận công ước và những quy định của WIPO làm nền tảng trong việc thương thảo các thỏa thuận thương mại song phương, đa phương, và cả khi gia nhập Tổ chức Thương mại thế giới (WTO). Mỹ là nước có kho tài sản trí tuệ quan trọng nhất hiện nay. Ở đó việc bảo hộ quyền sở hữu trí tuệ được chia làm bốn lĩnh vực, gồm bằng phát minh sáng chế (patents), thương hiệu và nhãn hiệu (trademarks), bản quyền và tác quyền (copyrights) và bí mật thương mại (trade secrets).</li>
				<li>Phạm vi điều chỉnh quyền sở hữu trí tuệ quan trọng nhất hiện nay thuộc về lĩnh vực thương mại điện tử. Bản thân công nghệ thông tin và hệ thống mạng Internet đã là một tập hợp to lớn không thể đếm hết những tài sản trí tuệ đa dạng và tinh túy nhất trong thời đại ngày nay. Như vậy, khi nền thương mại điện tử đặt căn bản vận hành trong môi trường kỹ thuật số thì nó mặc nhiên sử dụng các tài sản này trong hệ thống mạng, bao gồm cả các ứng dụng miễn phí hay trả tiền, cộng với những tài sản do chính hoạt động của thương mại điện tử tạo nên. Nền thương mại điện tử tăng trưởng rất nhanh và nay bao gồm nhiều lĩnh vực, nhiều phương cách với tốc độ phát triển sáng tạo mỗi ngày một nhanh. Tất cả đã bắt đầu từ sự khai sinh cấu trúc siêu liên kết World Wide Web (www) của Tim Berners-Lee năm 1992 gắn cho mỗi trang mạng một địa chỉ để từ đó bất cứ ai muốn tìm (truy cập) đến nó đều có thể gặp được. Năm 1994 lần đầu tiên người ta thấy xuất hiện tiệm bánh trực tuyến Pizza Hut. Nhưng từ 1998, nền thương mại điện tử bao gồm cả việc bán hàng và cung cấp dịch vụ mới thực sự cất cánh, cùng một lúc với sự ra đời của tổ chức ICANN đi tiên phong trong việc sắp xếp hợp lý hệ thống tên miền cho toàn thế giới.</li>
				<li>Mối tương quan tay trong tay giữa sở hữu trí tuệ và thương mại điện tử ngày càng chặt chẽ. Ngay từ những năm đầu, thương mại điện tử đã bày bán các sản phẩm hay dịch vụ dựa trên cơ sở quyền sở hữu trí tuệ và quyền cấp giấy phép sử dụng, ví dụ như băng nhạc, phim ảnh, phần mềm, bản vẽ thiết kế, giáo trình đào tạo… Bản chất mỗi tài sản sở hữu trí tuệ là một tài sản mà chủ sở hữu có thể buôn bán, trao đổi với người khác dưới dạng bằng sáng chế (patent) hay cấp giấy phép sử dụng (license) mà không cần kèm theo hàng hóa hay dịch vụ. Trong nhiều trường hợp tài sản sở hữu trí tuệ là thành phần giá trị chính của việc giao dịch. Trong nền thương mại điện tử chúng ta có những công ty dịch vụ Internet cung cấp phần mềm, mạng lưới, chip vi mạch, đường truyền, bộ chuyển mạch… và những công ty khai thác Internet vào mục đích thương mại thể hiện trên mỗi thương hiệu trực tuyến. Ở đây, chúng ta thấy bản thân các tài sản sở hữu trí tuệ là đối tượng giao dịch của thương mại điện tử, vì vậy việc bảo hộ quyền sở hữu trí tuệ đồng nghĩa với việc bảo đảm an toàn cho các hoạt động thương mại điện tử. Bất cứ hình thức xâm phạm nào đến các quyền sở hữu trí tuệ trong thương mại điện tử như đánh cắp thương hiệu hay cướp lấy tên miền đều làm cho việc kinh doanh của công ty bị tổn hại.</li>
				<li>Đối tượng cần được bảo hộ quyền sở hữu trí tuệ trong thương mại điện tử gồm ba nhóm: Bằng sáng chế (patent) tạo nên bởi tổ hợp các phần mềm để thực hiện chức năng thương mại điện tử đặc thù cho công ty; bản quyền (copyright) đối với trang web và cả những gì truyền đi trên trang web; và thương hiệu (trademark), bao gồm biểu tượng có giá trị và câu chữ giúp nhận diện công ty. Bản quyền cho phép chủ sở hữu có cơ sở pháp lý để bảo vệ công trình sáng tạo của mình không bị đánh cắp hay sử dụng trái phép. Trong trường hợp nội dung bản quyền gắn liền với vật thể như tờ giấy, tấm vải hay phần cứng thiết bị thì tác quyền mặc nhiên xuất hiện. Nhưng trong thương mại điện tử, tác quyền xuất hiện sớm hơn, nghĩa là ngay từ khi nội dung được sinh ra. Thương hiệu giúp cho người ta phân biệt sản phẩm hay dịch vụ của hãng này so với hãng khác. Một thương hiệu càng có giá trị cao khi càng được nhiều người biết, tin tưởng và yêu mến. Việc đánh giá tầm quan trọng của một công ty thương mại điện tử dựa trên giá trị và số lượng các tài sản trí tuệ được bảo hộ. Giá trị này một mặt tạo nên uy tín thương hiệu, mặt khác giúp định giá vốn hóa doanh nghiệp ở mỗi thời điểm, và cuối cùng được trưng dẫn mỗi khi xảy ra kiện tụng liên quan đến sở hữu trí tuệ, đặc biệt là bằng sáng chế, giữa các công ty trên những thị trường nhất định. </li>
				<li>Về mặt bản quyền, trang web thương mại điện tử của chúng tôi bao gồm nhiều thành phần với nhiều chất liệu trên đó. Những chất liệu cần được quan tâm bảo vệ nhất gồm phần mềm để chạy các chương trình trên trang web, văn bản và hình ảnh trên trang, thành phần âm thanh và cơ sở dữ liệu. Giá trị kinh tế lớn nhất của quyền sở hữu trí tuệ nằm ở chỗ nó được dùng để cấp phép cho các cá nhân hoặc doanh nghiệp khác sử dụng, hoặc dưới hình thức cấp phép sản phẩm như phần mềm chương trình, hoặc dưới chính sở hữu trí tuệ đó như cấp phép khai thác bằng sáng chế. Nhưng đây lại là những cái bẫy hoặc lỗ hổng lớn nhất khả dĩ làm cho một tài sản sở hữu trí tuệ có thể bị đánh cắp, biến mất hay suy yếu. Doanh nghiệp cần quan tâm đến nội dung và ngôn từ trong các hợp đồng có liên quan đến sở hữu trí tuệ, như trong việc thỏa thuận thiết kế hay phát triển trang web, thỏa thuận cho phép khai thác bằng sáng chế và thỏa thuận cho phép sử dụng tên miền và thương hiệu. Thông thường các doanh nghiệp thương mại điện tử thường lập cho mình bộ hồ sơ lưu trữ các hợp đồng có liên quan đến sở hữu trí tuệ để dùng vào mỗi lúc gọi vốn đầu tư bổ sung, bán tài sản, sáp nhập hoặc bán doanh nghiệp.</li>
			</ol>
		</section>
		<section class="section intellectual-property inner-bottom-xs">
			<h2>Chấm dứt tài khoản</h2>
			<ol>
				<li>Getthem bảo lưu quyền chấm dứt vĩnh viễn hoặc chấm dứt tạm thời hoạt động của Tài khoản nếu bạn được xác định đã vi phạm Quy chế tài khoản, Quy chế hoạt động, Quy định đăng tin và/hoặc có những hành vi ảnh hưởng đến hoạt động kinh doanh của Getthem, bạn sẽ được thông báo trước 05 (năm) ngày về việc Tài khoản bị chấm dứt hoặc tạm ngưng theo quy định của Getthem.</li>
				<li>Chúng tôi có quyền quyết định Tài khoản đó có vi phạm Quy chế tài khoản, Quy chế hoạt động, Quy định đăng tin hoặc có hành vi ảnh hưởng đến hoạt động của getthem.com hay không dựa trên những quy định mà chúng tôi đã công khai website Getthem hoặc khi có căn cứ cho rằng Tài khoản đó có hành vi vi phạm pháp luật. Thời điểm chấm dứt Tài khoản là khi Getthem gửi email cho bạn về việc chấm dứt Tài khoản.</li>
			</ol>
            <h2>Hậu quả của việc chấm dứt tài khoản</h2>
            <ol>
                <li>Nếu Tài khoản của bạn bị chấm dứt thì tất cả quyền của bạn liên quan đến Tài khoản cũng sẽ mặc nhiên bị chấm dứt.</li>
                <li>Bạn sẽ không thể đăng nhập vào Tài khoản đã chấm dứt. Bạn sẽ không thể tạo lại Tài khoản mới dựa trên Số điện thoại bạn đăng ký với Tài khoản đã chấm dứt trên Chợ Tốt. Bạn phải hiểu rằng bất kỳ khiếu nại nào liên quan đến việc tạo lại Tài khoản dựa trên số điện thoại của Tài khoản đã chấm dứt đều không được giải quyết. Bạn vẫn sẽ chịu trách nhiệm trước pháp luật về lịch sử sử dụng Tài khoản đã chấm dứt sau ngày chấm dứt Tài khoản. Bạn sẽ không thể đăng nhập vào Tài khoản Đồng Tốt gắn với Tài khoản đã chấm dứt. Trường hợp bạn còn Đồng Tốt chưa sử dụng hết thì sẽ không được hoàn trả lại. Trường hợp trong Tài khoản còn tồn tại Đồng Tốt, bất kể số lượng Đồng Tốt là bao nhiêu, thì bạn phải hiểu rằng Đồng Tốt sẽ mặc nhiên hết giá trị sử dụng. Bạn phải hiểu rằng bạn sẽ không có quyền yêu cầu Chợ Tốt đền bù, chi trả, thuyên chuyển cho người dùng khác hoặc quy đổi Đồng Tốt thành tiền mặt, tài sản khác. Vì lý do đó, bạn vui lòng cân nhắc ngân sách nạp và việc sử dụng Đồng Tốt phù hợp với nhu cầu thực tế của mình và cân nhắc trước khi chấm dứt Tài khoản mà chưa sử dụng hết. Sở dĩ, Chợ Tốt không phải là đơn vị có chức năng của ví điện tử nên việc quy đổi Đồng Tốt là không được phép theo quy định của pháp luật.</li>
            </ol>
		</section>
		<section class="section intellectual-property">
			<h2>Liên hệ với chúng tôi</h2>
			<p>Nếu bạn có bất cứ vấn đề gì với điều khoản của chúng tôi. Hãy liên lạc với chúng tôi <a href="contact.php">Tại đây</a></p>
		</section>
	</div>
</main>